import { useEffect, useState } from 'react'
import { toast } from 'react-toastify'
import { api } from '../api'

export default function Receipts() {
  const [orders, setOrders] = useState([])
  const [receipts, setReceipts] = useState([])
  const [orderId, setOrderId] = useState('')
  const [loading, setLoading] = useState(false)

  const loadOrders = async () => {
    try { const d = await api('/api/orders'); setOrders(d.content ?? d) } catch (e) { toast.error(e.message) }
  }

  useEffect(() => { loadOrders() }, [])

  const generate = async (e) => {
    e.preventDefault()
    if (!orderId) { toast.warn('Select an order'); return }
    setLoading(true)
    try {
      const receipt = await api(`/api/receipts/order/${orderId}`, { method: 'POST' })
      setReceipts(p => [receipt, ...p])
      toast.success('Receipt generated')
      setOrderId('')
    } catch (e) { toast.error(e.message) } finally { setLoading(false) }
  }

  const fetchReceipt = async (oid) => {
    try {
      const receipt = await api(`/api/receipts/order/${oid}`)
      setReceipts(p => {
        const exists = p.find(r => r.id === receipt.id)
        return exists ? p : [receipt, ...p]
      })
      toast.info('Receipt loaded')
    } catch (e) { toast.error(e.message) }
  }

  const download = (receiptId) => {
    window.open(`/api/receipts/${receiptId}/download`, '_blank')
  }

  return (
    <div className="space-y-6">
      <h2 className="text-2xl font-bold text-emerald-950">Receipts</h2>

      <form onSubmit={generate} className="flex gap-3 rounded-2xl border border-emerald-200 bg-white p-5 flex-wrap">
        <select value={orderId} onChange={e => setOrderId(e.target.value)} className="input flex-1">
          <option value="">Select Order to Generate Receipt</option>
          {orders.map(o => <option key={o.id} value={o.id}>#{o.orderNumber} — {o.customerName} — {o.totalAmount}</option>)}
        </select>
        <button type="submit" disabled={loading} className="btn-primary">Generate Receipt</button>
      </form>

      <div className="rounded-2xl border border-emerald-200 bg-white p-5 space-y-3">
        <p className="text-sm font-semibold text-emerald-950">Lookup Receipt by Order</p>
        <div className="flex gap-3 flex-wrap">
          <select onChange={e => e.target.value && fetchReceipt(e.target.value)} defaultValue="" className="input flex-1">
            <option value="">Select Order to Lookup Receipt</option>
            {orders.map(o => <option key={o.id} value={o.id}>#{o.orderNumber} — {o.customerName}</option>)}
          </select>
        </div>
      </div>

      {receipts.length > 0 && (
        <div className="overflow-x-auto rounded-2xl border border-emerald-200 bg-white">
          <table className="w-full text-sm">
            <thead className="bg-emerald-50 text-emerald-900">
              <tr>{['Receipt #', 'Order #', 'Total', 'Tax', 'Discount', 'Generated By', 'Date', 'Download'].map(h => <th key={h} className="px-4 py-3 text-left font-semibold">{h}</th>)}</tr>
            </thead>
            <tbody>
              {receipts.map(r => (
                <tr key={r.id} className="border-t border-emerald-100">
                  <td className="px-4 py-3">{r.receiptNumber}</td>
                  <td className="px-4 py-3">{r.orderNumber}</td>
                  <td className="px-4 py-3">{r.totalAmount}</td>
                  <td className="px-4 py-3">{r.taxAmount}</td>
                  <td className="px-4 py-3">{r.discountAmount}</td>
                  <td className="px-4 py-3">{r.generatedByName}</td>
                  <td className="px-4 py-3">{new Date(r.generatedAt).toLocaleDateString()}</td>
                  <td className="px-4 py-3">
                    <button onClick={() => download(r.id)} className="btn-xs-secondary">Download</button>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      )}
    </div>
  )
}
